### ISSUE TITLE
Seems unhappy on Windows 10

### ISSUE THREAD

**Issue by samilamti** [Vital-Utilities/Vital-Utilities#66]
### What happened?

Starting the application
![image](https://user-images.githubusercontent.com/1975185/174258136-da2436d4-421b-46e2-9f92-161c8d2a250d.png)

### What operating system are you seeing the problem on?

Windows 10

### Relevant log output

```shell
- Faulting application name: VitalService.exe, version: 0.0.7.0, time stamp: 0x6216d2c0
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1741, time stamp: 0xe9b4a91b
Exception code: 0xe0434352
Fault offset: 0x0000000000034fd9
Faulting process id: 0x5af8
Faulting application start time: 0x01d88222fe2085ba
Faulting application path: C:\Program Files\Vital Utilities\bin\VitalService\VitalService.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: ddbf67a2-f8d6-45fd-bb40-ebaf4f33149d
Faulting package full name: 
Faulting package-relative application ID: 

- Application: VitalService.exe
CoreCLR Version: 6.0.322.12309
.NET Version: 6.0.3
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'table "__EFMigrationsHistory" already exists'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at lambda_method2(Closure , IServiceProvider , DbContextOptions`1 )
   at Microsoft.EntityFrameworkCore.Internal.DbContextFactory`1.CreateDbContext()
   at VitalService.Services.MetricsStorageService.<>c__DisplayClass28_0.<<LoadDbIntoCache>b__0>d.MoveNext() in D:\a\Vital-Utilities\Vital-Utilities\Source\Services\VitalService\VitalService\Services\MetricsStorageService.cs:line 83
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

- Category: Microsoft.AspNetCore.Server.Kestrel
EventId: 13
SpanId: 04ad1852a271d02e
TraceId: 68b97f8e221fa9e30e2a0d4a333712c4
ParentId: 0000000000000000
ConnectionId: 0HMIG78J0A8MB
RequestId: 0HMIG78J0A8MB:00000005
RequestPath: /api/Process/Managed

Connection id "0HMIG78J0A8MB", Request id "0HMIG78J0A8MB:00000005": An unhandled exception was thrown by the application.

Exception: 
System.InvalidOperationException: The exception handler configured on ExceptionHandlerOptions produced a 404 status response. This InvalidOperationException containing the original exception was thrown since this is often due to a misconfigured ExceptionHandlingPath. If the exception handler is expected to return 404 status responses then set AllowStatusCode404Response to true.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'table "__EFMigrationsHistory" already exists'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at lambda_method1(Closure , IServiceProvider , DbContextOptions`1 )
   at Microsoft.EntityFrameworkCore.Internal.DbContextFactory`1.CreateDbContext()
   at VitalService.Stores.ManagedProcessStore.GetAsync() in D:\a\Vital-Utilities\Vital-Utilities\Source\Services\VitalService\VitalService\Stores\ManagedProcessStore.cs:line 26
   at VitalService.Controllers.ProcessController.GetManagedAsync() in D:\a\Vital-Utilities\Vital-Utilities\Source\Services\VitalService\VitalService\Controllers\ProcessController.cs:line 51
   at lambda_method21(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatcher|8_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task`1 matcherTask)
   at VitalService.Startup.<>c.<<Configure>b__6_0>d.MoveNext() in D:\a\Vital-Utilities\Vital-Utilities\Source\Services\VitalService\VitalService\Startup.cs:line 118
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Sentry.AspNetCore.SentryMiddleware.InvokeAsync(HttpContext context) in /_/src/Sentry.AspNetCore/SentryMiddleware.cs:line 108
   at Sentry.AspNetCore.SentryMiddleware.InvokeAsync(HttpContext context) in /_/src/Sentry.AspNetCore/SentryMiddleware.cs:line 129
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

- Category: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware
EventId: 1
SpanId: 04ad1852a271d02e
TraceId: 68b97f8e221fa9e30e2a0d4a333712c4
ParentId: 0000000000000000
ConnectionId: 0HMIG78J0A8MB
RequestId: 0HMIG78J0A8MB:00000005
RequestPath: /api/Process/Managed

An unhandled exception has occurred while executing the request.

Exception: 
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'table "__EFMigrationsHistory" already exists'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at lambda_method1(Closure , IServiceProvider , DbContextOptions`1 )
   at Microsoft.EntityFrameworkCore.Internal.DbContextFactory`1.CreateDbContext()
   at VitalService.Stores.ManagedProcessStore.GetAsync() in D:\a\Vital-Utilities\Vital-Utilities\Source\Services\VitalService\VitalService\Stores\ManagedProcessStore.cs:line 26
   at VitalService.Controllers.ProcessController.GetManagedAsync() in D:\a\Vital-Utilities\Vital-Utilities\Source\Services\VitalService\VitalService\Controllers\ProcessController.cs:line 51
   at lambda_method21(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatcher|8_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task`1 matcherTask)
   at VitalService.Startup.<>c.<<Configure>b__6_0>d.MoveNext() in D:\a\Vital-Utilities\Vital-Utilities\Source\Services\VitalService\VitalService\Startup.cs:line 118
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

- Category: Microsoft.EntityFrameworkCore.Database.Command
EventId: 20102
SpanId: 04ad1852a271d02e
TraceId: 68b97f8e221fa9e30e2a0d4a333712c4
ParentId: 0000000000000000
ConnectionId: 0HMIG78J0A8MB
RequestId: 0HMIG78J0A8MB:00000005
RequestPath: /api/Process/Managed
ActionId: bcb2f5a7-5e42-4783-8058-f67f3f4620f9
ActionName: VitalService.Controllers.ProcessController.GetManagedAsync (VitalService)

Failed executing DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE "__EFMigrationsHistory" (
    "MigrationId" TEXT NOT NULL CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY,
    "ProductVersion" TEXT NOT NULL
);

- Category: Microsoft.EntityFrameworkCore.Database.Command
EventId: 20102

Failed executing DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE "__EFMigrationsHistory" (
    "MigrationId" TEXT NOT NULL CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY,
    "ProductVersion" TEXT NOT NULL
);
```

### This bug exists on the latest released version of the software

- [X] I confirm this bug exists on the latest version of the software

**Comment by Snazzie** [comment]
One possible cause is that im doing db.migrate inside constructor of DbContext. Could be that multiple AppDbContext instances got instantiated and they were all trying to do migrate on same db. Might have to move the db.migrate into startup.
